const Systemic = require('systemic')
const Config = require('./components/config')
const Logger = require('./components/logger')
const mysqlSys = require('./components/mysql')
const karmaBot = require('./components/karmabot')
const karmaController = require('./src/controllers/karmaController')
//const bot = require('./src/bot')

module.exports = () => Systemic()
    .add('config', Config(), { scoped: true })
    .add('logger', Logger()).dependsOn('config')
    .add('mysqlSys', mysqlSys()).dependsOn('config', 'loger')
    .add('karmabot', karmaBot(karmaController)).dependsOn('config', 'loger')
